import type { Metadata } from "next";
import { Roboto, Libre_Baskerville } from "next/font/google";
import "./globals.css";

const lb = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lb",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lb.variable} ${roboto.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
